name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Determine image tag
      id: vars
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 379809513/demo-biz:${{ steps.vars.outputs.TAG }}
      
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 379809513/demo-biz:${{ steps.vars.outputs.TAG }}
